### ISSUE TITLE
Always handle possible promise rejections

### ISSUE THREAD

**Issue by oliverjam** [fac24/week2-Bereket-Hallie-Joe-Petra#38]
https://github.com/fac24/week2-Bereket-Hallie-Joe-Petra/blob/2404dd6fac72e98f1756473191fa85bf13a99bc1/routes/addReview.js#L52-L67

I just crashed your app (sorry!) by inserting a username that was over 255 characters long. Since the column is defined as `VARCHAR(255)` this caused the DB to throw an error on insert, causing your promise to reject. This means the `.then` does not run, which means your handler never sends a response.

To fix this you need to make sure your handlers always have `.catch`s on any promises. Think of a promise like a branch in the code (kind of like an if/else). If you only send a response in _one branch_ then at least some of the time users will hit the other branch and your handler just won't send a response at all (this kills the Heroku).

**Comment by oliverjam** [comment]
(sidenot it's probably fine to just use `TEXT` for most string fields, unless you really want to limit characters. DBs have lots of storage space nowadays. If you do want to restrict it you should probably tell the user/validate their input so they know the limitation)

**Comment by joe-dev-public** [comment]
Related to #25 and #33
